### ISSUE TITLE
error at the project rebuilding

### ISSUE THREAD

**Issue by m00nk** [lewyuburi/nuxt-validate#8]
If I make some changes in nuxt.config.js when the dev-server is running, the dev-server rebuilds the project automatically and I get the error:

>  ERROR  MomentLocalesPlugin: Moment.js doesn’t include a locale you specified: ru. Check the plugin’s localesToKeep option.                                                                                               14:07:13
You can see the full list of locales that Moment.js includes in node_modules/moment/locale/
  You can see the full list of locales that Moment.js includes in node_modules/moment/locale/
  at normalizeLocalesToKeep (node_modules/moment-locales-webpack-plugin/index.js:67:15)
  at checkOptions (node_modules/moment-locales-webpack-plugin/index.js:31:25)
  at new MomentLocalesPlugin (node_modules/moment-locales-webpack-plugin/index.js:87:29)
  at WebpackBundler.extendBuild (node_modules/@nuxtjs/moment/lib/module.js:18:25)
  at WebpackBundler.<anonymous> (node_modules/@nuxt/utils/dist/utils.js:1812:25)
  at WebpackClientConfig.extendConfig (node_modules/@nuxt/webpack/dist/webpack.js:4766:37)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4796:45)
  at WebpackClientConfig.config (node_modules/@nuxt/webpack/dist/webpack.js:4965:26)
  at WebpackBundler.getWebpackConfig (node_modules/@nuxt/webpack/dist/webpack.js:5267:19)
  at WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5274:12)
  at Builder.build (node_modules/@nuxt/builder/dist/builder.js:5578:30)

If I stop the dev-server and run it again (`nuxt build`) the error does not appear.

My config:
`['nuxt-validate', {lang: 'ru'}],`

**Comment by lewyuburi** [comment]
> ERROR MomentLocalesPlugin: Moment.js doesn’t include a locale you specified: ru. Check the plugin’s localesToKeep option. 14:07:13
You can see the full list of locales that Moment.js includes in node_modules/moment/locale/
You can see the full list of locales that Moment.js includes in node_modules/moment/locale/

Apparently it is a Momentjs's error
